// Mocks generated by Mockito 5.4.6 from annotations
// in codebase/test/features/profile/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:codebase/core/error/failures.dart' as _i19;
import 'package:codebase/core/usecases/usecase.dart' as _i21;
import 'package:codebase/features/profile/data/datasources/profile_remote_datasource.dart'
    as _i10;
import 'package:codebase/features/profile/data/models/change_company_password_model.dart'
    as _i2;
import 'package:codebase/features/profile/data/models/change_student_password_model.dart'
    as _i4;
import 'package:codebase/features/profile/data/models/get_company_profile_model.dart'
    as _i5;
import 'package:codebase/features/profile/data/models/get_student_profile_model.dart'
    as _i6;
import 'package:codebase/features/profile/data/models/update_company_profile_model.dart'
    as _i7;
import 'package:codebase/features/profile/data/models/update_company_user_profile_model.dart'
    as _i3;
import 'package:codebase/features/profile/data/models/update_student_profile_model.dart'
    as _i8;
import 'package:codebase/features/profile/domain/entities/get_student_profile_response.dart'
    as _i20;
import 'package:codebase/features/profile/domain/repositories/profile_repo.dart'
    as _i9;
import 'package:codebase/features/profile/domain/usecases/change_company_password_usecase.dart'
    as _i12;
import 'package:codebase/features/profile/domain/usecases/change_student_password_usecase.dart'
    as _i14;
import 'package:codebase/features/profile/domain/usecases/get_student_profile_usecase.dart'
    as _i17;
import 'package:codebase/features/profile/domain/usecases/update_company_profile_usecase.dart'
    as _i15;
import 'package:codebase/features/profile/domain/usecases/update_company_user_profile_usecase.dart'
    as _i13;
import 'package:codebase/features/profile/domain/usecases/update_student_profile_usecase.dart'
    as _i16;
import 'package:either/either.dart' as _i18;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i22;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeChangeCompanyPasswordModel_0 extends _i1.SmartFake
    implements _i2.ChangeCompanyPasswordModel {
  _FakeChangeCompanyPasswordModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateCompanyUserProfileModel_1 extends _i1.SmartFake
    implements _i3.UpdateCompanyUserProfileModel {
  _FakeUpdateCompanyUserProfileModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChangeStudentPasswordModel_2 extends _i1.SmartFake
    implements _i4.ChangeStudentPasswordModel {
  _FakeChangeStudentPasswordModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetCompanyProfileModel_3 extends _i1.SmartFake
    implements _i5.GetCompanyProfileModel {
  _FakeGetCompanyProfileModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetStudentProfileModel_4 extends _i1.SmartFake
    implements _i6.GetStudentProfileModel {
  _FakeGetStudentProfileModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateCompanyProfileModel_5 extends _i1.SmartFake
    implements _i7.UpdateCompanyProfileModel {
  _FakeUpdateCompanyProfileModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStudentProfileModel_6 extends _i1.SmartFake
    implements _i8.UpdateStudentProfileModel {
  _FakeUpdateStudentProfileModel_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileRepository_7 extends _i1.SmartFake
    implements _i9.ProfileRepository {
  _FakeProfileRepository_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSource extends _i1.Mock
    implements _i10.ProfileRemoteDataSource {
  MockProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.ChangeCompanyPasswordModel> changeCompanyPassword(
          {required _i12.ChangeCompanyPasswordParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeCompanyPassword,
          [],
          {#params: params},
        ),
        returnValue: _i11.Future<_i2.ChangeCompanyPasswordModel>.value(
            _FakeChangeCompanyPasswordModel_0(
          this,
          Invocation.method(
            #changeCompanyPassword,
            [],
            {#params: params},
          ),
        )),
      ) as _i11.Future<_i2.ChangeCompanyPasswordModel>);

  @override
  _i11.Future<_i3.UpdateCompanyUserProfileModel> updateCompanyUserProfile(
          {required _i13.UpdateCompanyUserProfileParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCompanyUserProfile,
          [],
          {#params: params},
        ),
        returnValue: _i11.Future<_i3.UpdateCompanyUserProfileModel>.value(
            _FakeUpdateCompanyUserProfileModel_1(
          this,
          Invocation.method(
            #updateCompanyUserProfile,
            [],
            {#params: params},
          ),
        )),
      ) as _i11.Future<_i3.UpdateCompanyUserProfileModel>);

  @override
  _i11.Future<_i4.ChangeStudentPasswordModel> changeStudentPassword(
          {required _i14.ChangeStudentPasswordParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeStudentPassword,
          [],
          {#params: params},
        ),
        returnValue: _i11.Future<_i4.ChangeStudentPasswordModel>.value(
            _FakeChangeStudentPasswordModel_2(
          this,
          Invocation.method(
            #changeStudentPassword,
            [],
            {#params: params},
          ),
        )),
      ) as _i11.Future<_i4.ChangeStudentPasswordModel>);

  @override
  _i11.Future<_i5.GetCompanyProfileModel> getCompanyProfile() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompanyProfile,
          [],
        ),
        returnValue: _i11.Future<_i5.GetCompanyProfileModel>.value(
            _FakeGetCompanyProfileModel_3(
          this,
          Invocation.method(
            #getCompanyProfile,
            [],
          ),
        )),
      ) as _i11.Future<_i5.GetCompanyProfileModel>);

  @override
  _i11.Future<_i6.GetStudentProfileModel> getStudentProfile() =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudentProfile,
          [],
        ),
        returnValue: _i11.Future<_i6.GetStudentProfileModel>.value(
            _FakeGetStudentProfileModel_4(
          this,
          Invocation.method(
            #getStudentProfile,
            [],
          ),
        )),
      ) as _i11.Future<_i6.GetStudentProfileModel>);

  @override
  _i11.Future<_i7.UpdateCompanyProfileModel> updateCompanyProfile(
          {required _i15.UpdateCompanyProfileParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCompanyProfile,
          [],
          {#params: params},
        ),
        returnValue: _i11.Future<_i7.UpdateCompanyProfileModel>.value(
            _FakeUpdateCompanyProfileModel_5(
          this,
          Invocation.method(
            #updateCompanyProfile,
            [],
            {#params: params},
          ),
        )),
      ) as _i11.Future<_i7.UpdateCompanyProfileModel>);

  @override
  _i11.Future<_i8.UpdateStudentProfileModel> updateStudentProfile(
          {required _i16.UpdateStudentProfileParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStudentProfile,
          [],
          {#params: params},
        ),
        returnValue: _i11.Future<_i8.UpdateStudentProfileModel>.value(
            _FakeUpdateStudentProfileModel_6(
          this,
          Invocation.method(
            #updateStudentProfile,
            [],
            {#params: params},
          ),
        )),
      ) as _i11.Future<_i8.UpdateStudentProfileModel>);
}

/// A class which mocks [GetStudentProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetStudentProfileUseCase extends _i1.Mock
    implements _i17.GetStudentProfileUseCase {
  MockGetStudentProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.ProfileRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProfileRepository_7(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i9.ProfileRepository);

  @override
  _i11.Future<_i18.Either<_i19.Failure, _i20.GetStudentProfileResponse>> call(
          _i21.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i11.Future<
                _i18
                .Either<_i19.Failure, _i20.GetStudentProfileResponse>>.value(
            _i22.dummyValue<
                _i18.Either<_i19.Failure, _i20.GetStudentProfileResponse>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i11
          .Future<_i18.Either<_i19.Failure, _i20.GetStudentProfileResponse>>);
}
