// Mocks generated by Mockito 5.4.6 from annotations
// in codebase/test/features/auth/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i14;

import 'package:codebase/core/api/dio_consumer.dart' as _i36;
import 'package:codebase/core/error/failures.dart' as _i21;
import 'package:codebase/core/usecases/usecase.dart' as _i15;
import 'package:codebase/core/utils/enums.dart' as _i18;
import 'package:codebase/features/auth/data/datasources/auth_local_datasource.dart'
    as _i16;
import 'package:codebase/features/auth/data/datasources/auth_remote_datasource.dart'
    as _i13;
import 'package:codebase/features/auth/data/datasources/avatar_picker.dart'
    as _i35;
import 'package:codebase/features/auth/data/datasources/social_auth_service.dart'
    as _i33;
import 'package:codebase/features/auth/data/models/complete_registration_model.dart'
    as _i8;
import 'package:codebase/features/auth/data/models/login_model.dart' as _i3;
import 'package:codebase/features/auth/data/models/logout_model.dart' as _i11;
import 'package:codebase/features/auth/data/models/register_model.dart' as _i2;
import 'package:codebase/features/auth/data/models/request_otp_model.dart'
    as _i5;
import 'package:codebase/features/auth/data/models/request_password_reset_model.dart'
    as _i9;
import 'package:codebase/features/auth/data/models/reset_password_model.dart'
    as _i10;
import 'package:codebase/features/auth/data/models/social_sign_in_model.dart'
    as _i7;
import 'package:codebase/features/auth/data/models/verify_email_model.dart'
    as _i4;
import 'package:codebase/features/auth/data/models/verify_phone_otp_model.dart'
    as _i6;
import 'package:codebase/features/auth/domain/entities/auth_session.dart'
    as _i17;
import 'package:codebase/features/auth/domain/entities/complete_registration_response.dart'
    as _i29;
import 'package:codebase/features/auth/domain/entities/login_response.dart'
    as _i24;
import 'package:codebase/features/auth/domain/entities/logout_response.dart'
    as _i32;
import 'package:codebase/features/auth/domain/entities/register_response.dart'
    as _i22;
import 'package:codebase/features/auth/domain/entities/registration_draft.dart'
    as _i19;
import 'package:codebase/features/auth/domain/entities/request_otp_response.dart'
    as _i26;
import 'package:codebase/features/auth/domain/entities/request_password_reset_response.dart'
    as _i30;
import 'package:codebase/features/auth/domain/entities/reset_password_response.dart'
    as _i31;
import 'package:codebase/features/auth/domain/entities/social_sign_in_response.dart'
    as _i28;
import 'package:codebase/features/auth/domain/entities/verify_email_response.dart'
    as _i25;
import 'package:codebase/features/auth/domain/entities/verify_phone_otp_response.dart'
    as _i27;
import 'package:codebase/features/auth/domain/enums/social_provider.dart'
    as _i34;
import 'package:codebase/features/auth/domain/repositories/auth_repo.dart'
    as _i12;
import 'package:codebase/features/auth/domain/usecases/complete_registration_usecase.dart'
    as _i47;
import 'package:codebase/features/auth/domain/usecases/continue_as_guest_usecase.dart'
    as _i43;
import 'package:codebase/features/auth/domain/usecases/login_usecase.dart'
    as _i42;
import 'package:codebase/features/auth/domain/usecases/logout_usecase.dart'
    as _i44;
import 'package:codebase/features/auth/domain/usecases/read_registration_draft_usecase.dart'
    as _i51;
import 'package:codebase/features/auth/domain/usecases/register_usecase.dart'
    as _i39;
import 'package:codebase/features/auth/domain/usecases/request_email_otp_usecase.dart'
    as _i41;
import 'package:codebase/features/auth/domain/usecases/request_password_reset_usecase.dart'
    as _i49;
import 'package:codebase/features/auth/domain/usecases/request_phone_otp_usecase.dart'
    as _i45;
import 'package:codebase/features/auth/domain/usecases/reset_password_usecase.dart'
    as _i50;
import 'package:codebase/features/auth/domain/usecases/resolve_visitor_state_usecase.dart'
    as _i38;
import 'package:codebase/features/auth/domain/usecases/social_sign_in_usecase.dart'
    as _i48;
import 'package:codebase/features/auth/domain/usecases/verify_email_usecase.dart'
    as _i40;
import 'package:codebase/features/auth/domain/usecases/verify_phone_otp_usecase.dart'
    as _i46;
import 'package:dio/dio.dart' as _i37;
import 'package:either/either.dart' as _i20;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i23;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRegisterModel_0 extends _i1.SmartFake implements _i2.RegisterModel {
  _FakeRegisterModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginModel_1 extends _i1.SmartFake implements _i3.LoginModel {
  _FakeLoginModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyEmailModel_2 extends _i1.SmartFake
    implements _i4.VerifyEmailModel {
  _FakeVerifyEmailModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRequestOtpModel_3 extends _i1.SmartFake
    implements _i5.RequestOtpModel {
  _FakeRequestOtpModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyPhoneOtpModel_4 extends _i1.SmartFake
    implements _i6.VerifyPhoneOtpModel {
  _FakeVerifyPhoneOtpModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSocialSignInModel_5 extends _i1.SmartFake
    implements _i7.SocialSignInModel {
  _FakeSocialSignInModel_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCompleteRegistrationModel_6 extends _i1.SmartFake
    implements _i8.CompleteRegistrationModel {
  _FakeCompleteRegistrationModel_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRequestPasswordResetModel_7 extends _i1.SmartFake
    implements _i9.RequestPasswordResetModel {
  _FakeRequestPasswordResetModel_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordModel_8 extends _i1.SmartFake
    implements _i10.ResetPasswordModel {
  _FakeResetPasswordModel_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogoutModel_9 extends _i1.SmartFake implements _i11.LogoutModel {
  _FakeLogoutModel_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_10 extends _i1.SmartFake
    implements _i12.AuthRepository {
  _FakeAuthRepository_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i13.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i2.RegisterModel> register({required _i15.Params? params}) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {#params: params}),
            returnValue: _i14.Future<_i2.RegisterModel>.value(
              _FakeRegisterModel_0(
                this,
                Invocation.method(#register, [], {#params: params}),
              ),
            ),
          )
          as _i14.Future<_i2.RegisterModel>);

  @override
  _i14.Future<_i3.LoginModel> login({required _i15.Params? params}) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#params: params}),
            returnValue: _i14.Future<_i3.LoginModel>.value(
              _FakeLoginModel_1(
                this,
                Invocation.method(#login, [], {#params: params}),
              ),
            ),
          )
          as _i14.Future<_i3.LoginModel>);

  @override
  _i14.Future<_i4.VerifyEmailModel> verifyEmail({
    required _i15.Params? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#params: params}),
            returnValue: _i14.Future<_i4.VerifyEmailModel>.value(
              _FakeVerifyEmailModel_2(
                this,
                Invocation.method(#verifyEmail, [], {#params: params}),
              ),
            ),
          )
          as _i14.Future<_i4.VerifyEmailModel>);

  @override
  _i14.Future<_i5.RequestOtpModel> requestEmailOtp({
    required _i15.Params? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestEmailOtp, [], {#params: params}),
            returnValue: _i14.Future<_i5.RequestOtpModel>.value(
              _FakeRequestOtpModel_3(
                this,
                Invocation.method(#requestEmailOtp, [], {#params: params}),
              ),
            ),
          )
          as _i14.Future<_i5.RequestOtpModel>);

  @override
  _i14.Future<_i5.RequestOtpModel> requestPhoneOtp({
    required _i15.Params? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestPhoneOtp, [], {#params: params}),
            returnValue: _i14.Future<_i5.RequestOtpModel>.value(
              _FakeRequestOtpModel_3(
                this,
                Invocation.method(#requestPhoneOtp, [], {#params: params}),
              ),
            ),
          )
          as _i14.Future<_i5.RequestOtpModel>);

  @override
  _i14.Future<_i6.VerifyPhoneOtpModel> verifyPhoneOtp({
    required _i15.Params? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneOtp, [], {#params: params}),
            returnValue: _i14.Future<_i6.VerifyPhoneOtpModel>.value(
              _FakeVerifyPhoneOtpModel_4(
                this,
                Invocation.method(#verifyPhoneOtp, [], {#params: params}),
              ),
            ),
          )
          as _i14.Future<_i6.VerifyPhoneOtpModel>);

  @override
  _i14.Future<_i7.SocialSignInModel> socialSignIn({
    required _i15.Params? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#socialSignIn, [], {#params: params}),
            returnValue: _i14.Future<_i7.SocialSignInModel>.value(
              _FakeSocialSignInModel_5(
                this,
                Invocation.method(#socialSignIn, [], {#params: params}),
              ),
            ),
          )
          as _i14.Future<_i7.SocialSignInModel>);

  @override
  _i14.Future<_i8.CompleteRegistrationModel> completeRegistration({
    required _i15.Params? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeRegistration, [], {#params: params}),
            returnValue: _i14.Future<_i8.CompleteRegistrationModel>.value(
              _FakeCompleteRegistrationModel_6(
                this,
                Invocation.method(#completeRegistration, [], {#params: params}),
              ),
            ),
          )
          as _i14.Future<_i8.CompleteRegistrationModel>);

  @override
  _i14.Future<_i9.RequestPasswordResetModel> requestPasswordReset({
    required _i15.Params? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, [], {#params: params}),
            returnValue: _i14.Future<_i9.RequestPasswordResetModel>.value(
              _FakeRequestPasswordResetModel_7(
                this,
                Invocation.method(#requestPasswordReset, [], {#params: params}),
              ),
            ),
          )
          as _i14.Future<_i9.RequestPasswordResetModel>);

  @override
  _i14.Future<_i10.ResetPasswordModel> resetPassword({
    required _i15.Params? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#params: params}),
            returnValue: _i14.Future<_i10.ResetPasswordModel>.value(
              _FakeResetPasswordModel_8(
                this,
                Invocation.method(#resetPassword, [], {#params: params}),
              ),
            ),
          )
          as _i14.Future<_i10.ResetPasswordModel>);

  @override
  _i14.Future<_i11.LogoutModel> logout({required _i15.Params? params}) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [], {#params: params}),
            returnValue: _i14.Future<_i11.LogoutModel>.value(
              _FakeLogoutModel_9(
                this,
                Invocation.method(#logout, [], {#params: params}),
              ),
            ),
          )
          as _i14.Future<_i11.LogoutModel>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i16.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<void> persistSession(_i17.AuthSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#persistSession, [session]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> markGuest() =>
      (super.noSuchMethod(
            Invocation.method(#markGuest, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<_i18.UserType> readVisitorState() =>
      (super.noSuchMethod(
            Invocation.method(#readVisitorState, []),
            returnValue: _i14.Future<_i18.UserType>.value(
              _i18.UserType.firstOpen,
            ),
          )
          as _i14.Future<_i18.UserType>);

  @override
  _i14.Future<void> saveRegistrationDraft(_i19.RegistrationDraft? draft) =>
      (super.noSuchMethod(
            Invocation.method(#saveRegistrationDraft, [draft]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<_i19.RegistrationDraft?> readRegistrationDraft() =>
      (super.noSuchMethod(
            Invocation.method(#readRegistrationDraft, []),
            returnValue: _i14.Future<_i19.RegistrationDraft?>.value(),
          )
          as _i14.Future<_i19.RegistrationDraft?>);

  @override
  _i14.Future<void> clearRegistrationDraft() =>
      (super.noSuchMethod(
            Invocation.method(#clearRegistrationDraft, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i12.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i22.RegisterResponse>> register({
    required _i15.Params? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {#params: params}),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i22.RegisterResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i22.RegisterResponse>
                  >(this, Invocation.method(#register, [], {#params: params})),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i22.RegisterResponse>>);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i24.LoginResponse>> login({
    required _i15.Params? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#params: params}),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i24.LoginResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i24.LoginResponse>
                  >(this, Invocation.method(#login, [], {#params: params})),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i24.LoginResponse>>);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i25.VerifyEmailResponse>> verifyEmail({
    required _i15.Params? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#params: params}),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i25.VerifyEmailResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i25.VerifyEmailResponse>
                  >(
                    this,
                    Invocation.method(#verifyEmail, [], {#params: params}),
                  ),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i25.VerifyEmailResponse>>);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i26.RequestOtpResponse>>
  requestEmailOtp({required _i15.Params? params}) =>
      (super.noSuchMethod(
            Invocation.method(#requestEmailOtp, [], {#params: params}),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i26.RequestOtpResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i26.RequestOtpResponse>
                  >(
                    this,
                    Invocation.method(#requestEmailOtp, [], {#params: params}),
                  ),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i26.RequestOtpResponse>>);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i26.RequestOtpResponse>>
  requestPhoneOtp({required _i15.Params? params}) =>
      (super.noSuchMethod(
            Invocation.method(#requestPhoneOtp, [], {#params: params}),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i26.RequestOtpResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i26.RequestOtpResponse>
                  >(
                    this,
                    Invocation.method(#requestPhoneOtp, [], {#params: params}),
                  ),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i26.RequestOtpResponse>>);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i27.VerifyPhoneOtpResponse>>
  verifyPhoneOtp({required _i15.Params? params}) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneOtp, [], {#params: params}),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i27.VerifyPhoneOtpResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i27.VerifyPhoneOtpResponse>
                  >(
                    this,
                    Invocation.method(#verifyPhoneOtp, [], {#params: params}),
                  ),
                ),
          )
          as _i14.Future<
            _i20.Either<_i21.Failure, _i27.VerifyPhoneOtpResponse>
          >);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i28.SocialSignInResponse>>
  socialSignIn({required _i15.Params? params}) =>
      (super.noSuchMethod(
            Invocation.method(#socialSignIn, [], {#params: params}),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i28.SocialSignInResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i28.SocialSignInResponse>
                  >(
                    this,
                    Invocation.method(#socialSignIn, [], {#params: params}),
                  ),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i28.SocialSignInResponse>>);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i29.CompleteRegistrationResponse>>
  completeRegistration({required _i15.Params? params}) =>
      (super.noSuchMethod(
            Invocation.method(#completeRegistration, [], {#params: params}),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i29.CompleteRegistrationResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i29.CompleteRegistrationResponse>
                  >(
                    this,
                    Invocation.method(#completeRegistration, [], {
                      #params: params,
                    }),
                  ),
                ),
          )
          as _i14.Future<
            _i20.Either<_i21.Failure, _i29.CompleteRegistrationResponse>
          >);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i30.RequestPasswordResetResponse>>
  requestPasswordReset({required _i15.Params? params}) =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, [], {#params: params}),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i30.RequestPasswordResetResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i30.RequestPasswordResetResponse>
                  >(
                    this,
                    Invocation.method(#requestPasswordReset, [], {
                      #params: params,
                    }),
                  ),
                ),
          )
          as _i14.Future<
            _i20.Either<_i21.Failure, _i30.RequestPasswordResetResponse>
          >);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i31.ResetPasswordResponse>>
  resetPassword({required _i15.Params? params}) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#params: params}),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i31.ResetPasswordResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i31.ResetPasswordResponse>
                  >(
                    this,
                    Invocation.method(#resetPassword, [], {#params: params}),
                  ),
                ),
          )
          as _i14.Future<
            _i20.Either<_i21.Failure, _i31.ResetPasswordResponse>
          >);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i32.LogoutResponse>> logout({
    required _i15.Params? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [], {#params: params}),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i32.LogoutResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i32.LogoutResponse>
                  >(this, Invocation.method(#logout, [], {#params: params})),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i32.LogoutResponse>>);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i18.UserType>> resolveVisitorState({
    required _i15.Params? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resolveVisitorState, [], {#params: params}),
            returnValue:
                _i14.Future<_i20.Either<_i21.Failure, _i18.UserType>>.value(
                  _i23.dummyValue<_i20.Either<_i21.Failure, _i18.UserType>>(
                    this,
                    Invocation.method(#resolveVisitorState, [], {
                      #params: params,
                    }),
                  ),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i18.UserType>>);

  @override
  _i14.Future<_i20.Either<_i21.Failure, void>> continueAsGuest({
    required _i15.Params? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#continueAsGuest, [], {#params: params}),
            returnValue: _i14.Future<_i20.Either<_i21.Failure, void>>.value(
              _i23.dummyValue<_i20.Either<_i21.Failure, void>>(
                this,
                Invocation.method(#continueAsGuest, [], {#params: params}),
              ),
            ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, void>>);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i19.RegistrationDraft?>>
  readRegistrationDraft({required _i15.Params? params}) =>
      (super.noSuchMethod(
            Invocation.method(#readRegistrationDraft, [], {#params: params}),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i19.RegistrationDraft?>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i19.RegistrationDraft?>
                  >(
                    this,
                    Invocation.method(#readRegistrationDraft, [], {
                      #params: params,
                    }),
                  ),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i19.RegistrationDraft?>>);
}

/// A class which mocks [SocialAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialAuthService extends _i1.Mock implements _i33.SocialAuthService {
  MockSocialAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i33.SocialCredential> authorize(_i34.SocialProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#authorize, [provider]),
            returnValue: _i14.Future<_i33.SocialCredential>.value(
              _i23.dummyValue<_i33.SocialCredential>(
                this,
                Invocation.method(#authorize, [provider]),
              ),
            ),
          )
          as _i14.Future<_i33.SocialCredential>);
}

/// A class which mocks [AvatarPicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockAvatarPicker extends _i1.Mock implements _i35.AvatarPicker {
  MockAvatarPicker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<String?> pickAvatar() =>
      (super.noSuchMethod(
            Invocation.method(#pickAvatar, []),
            returnValue: _i14.Future<String?>.value(),
          )
          as _i14.Future<String?>);
}

/// A class which mocks [DioConsumer].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioConsumer extends _i1.Mock implements _i36.DioConsumer {
  MockDioConsumer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<dynamic> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? body,
    _i37.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #queryParameters: queryParameters,
                #body: body,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i14.Future<dynamic>.value(),
          )
          as _i14.Future<dynamic>);

  @override
  _i14.Future<dynamic> post(
    String? path, {
    _i37.FormData? formData,
    Map<String, dynamic>? body,
    Map<String, dynamic>? queryParameters,
    _i37.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #formData: formData,
                #body: body,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i14.Future<dynamic>.value(),
          )
          as _i14.Future<dynamic>);

  @override
  _i14.Future<dynamic> put(
    String? path, {
    _i37.FormData? formData,
    Map<String, dynamic>? body,
    Map<String, dynamic>? queryParameters,
    _i37.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #formData: formData,
                #body: body,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i14.Future<dynamic>.value(),
          )
          as _i14.Future<dynamic>);

  @override
  _i14.Future<dynamic> patch(
    String? path, {
    _i37.FormData? formData,
    Map<String, dynamic>? body,
    Map<String, dynamic>? queryParameters,
    _i37.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #formData: formData,
                #body: body,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i14.Future<dynamic>.value(),
          )
          as _i14.Future<dynamic>);

  @override
  _i14.Future<dynamic> delete(
    String? path, {
    _i37.FormData? formData,
    Map<String, dynamic>? body,
    Map<String, dynamic>? queryParameters,
    _i37.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #formData: formData,
                #body: body,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i14.Future<dynamic>.value(),
          )
          as _i14.Future<dynamic>);
}

/// A class which mocks [ResolveVisitorStateUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResolveVisitorStateUseCase extends _i1.Mock
    implements _i38.ResolveVisitorStateUseCase {
  MockResolveVisitorStateUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_10(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.AuthRepository);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i18.UserType>> call(
    _i15.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<_i20.Either<_i21.Failure, _i18.UserType>>.value(
                  _i23.dummyValue<_i20.Either<_i21.Failure, _i18.UserType>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i18.UserType>>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i39.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_10(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.AuthRepository);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i22.RegisterResponse>> call(
    _i39.RegisterParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i22.RegisterResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i22.RegisterResponse>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i22.RegisterResponse>>);
}

/// A class which mocks [VerifyEmailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyEmailUseCase extends _i1.Mock
    implements _i40.VerifyEmailUseCase {
  MockVerifyEmailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_10(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.AuthRepository);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i25.VerifyEmailResponse>> call(
    _i40.VerifyEmailParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i25.VerifyEmailResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i25.VerifyEmailResponse>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i25.VerifyEmailResponse>>);
}

/// A class which mocks [RequestEmailOtpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestEmailOtpUseCase extends _i1.Mock
    implements _i41.RequestEmailOtpUseCase {
  MockRequestEmailOtpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_10(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.AuthRepository);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i26.RequestOtpResponse>> call(
    _i41.RequestEmailOtpParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i26.RequestOtpResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i26.RequestOtpResponse>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i26.RequestOtpResponse>>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i42.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_10(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.AuthRepository);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i24.LoginResponse>> call(
    _i42.LoginParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i24.LoginResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i24.LoginResponse>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i24.LoginResponse>>);
}

/// A class which mocks [ContinueAsGuestUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockContinueAsGuestUseCase extends _i1.Mock
    implements _i43.ContinueAsGuestUseCase {
  MockContinueAsGuestUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_10(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.AuthRepository);

  @override
  _i14.Future<_i20.Either<_i21.Failure, void>> call(_i15.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i14.Future<_i20.Either<_i21.Failure, void>>.value(
              _i23.dummyValue<_i20.Either<_i21.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, void>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i44.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_10(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.AuthRepository);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i32.LogoutResponse>> call(
    _i15.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i32.LogoutResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i32.LogoutResponse>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i32.LogoutResponse>>);
}

/// A class which mocks [RequestPhoneOtpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestPhoneOtpUseCase extends _i1.Mock
    implements _i45.RequestPhoneOtpUseCase {
  MockRequestPhoneOtpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_10(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.AuthRepository);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i26.RequestOtpResponse>> call(
    _i45.RequestPhoneOtpParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i26.RequestOtpResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i26.RequestOtpResponse>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i26.RequestOtpResponse>>);
}

/// A class which mocks [VerifyPhoneOtpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyPhoneOtpUseCase extends _i1.Mock
    implements _i46.VerifyPhoneOtpUseCase {
  MockVerifyPhoneOtpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_10(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.AuthRepository);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i27.VerifyPhoneOtpResponse>> call(
    _i46.VerifyPhoneOtpParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i27.VerifyPhoneOtpResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i27.VerifyPhoneOtpResponse>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i14.Future<
            _i20.Either<_i21.Failure, _i27.VerifyPhoneOtpResponse>
          >);
}

/// A class which mocks [CompleteRegistrationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompleteRegistrationUseCase extends _i1.Mock
    implements _i47.CompleteRegistrationUseCase {
  MockCompleteRegistrationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_10(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.AuthRepository);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i29.CompleteRegistrationResponse>>
  call(_i47.CompleteRegistrationParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i29.CompleteRegistrationResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i29.CompleteRegistrationResponse>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i14.Future<
            _i20.Either<_i21.Failure, _i29.CompleteRegistrationResponse>
          >);
}

/// A class which mocks [SocialSignInUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialSignInUseCase extends _i1.Mock
    implements _i48.SocialSignInUseCase {
  MockSocialSignInUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_10(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.AuthRepository);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i28.SocialSignInResponse>> call(
    _i48.SocialSignInParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i28.SocialSignInResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i28.SocialSignInResponse>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i28.SocialSignInResponse>>);
}

/// A class which mocks [RequestPasswordResetUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestPasswordResetUseCase extends _i1.Mock
    implements _i49.RequestPasswordResetUseCase {
  MockRequestPasswordResetUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_10(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.AuthRepository);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i30.RequestPasswordResetResponse>>
  call(_i49.RequestPasswordResetParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i30.RequestPasswordResetResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i30.RequestPasswordResetResponse>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i14.Future<
            _i20.Either<_i21.Failure, _i30.RequestPasswordResetResponse>
          >);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i50.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_10(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.AuthRepository);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i31.ResetPasswordResponse>> call(
    _i50.ResetPasswordParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i31.ResetPasswordResponse>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i31.ResetPasswordResponse>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i14.Future<
            _i20.Either<_i21.Failure, _i31.ResetPasswordResponse>
          >);
}

/// A class which mocks [ReadRegistrationDraftUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadRegistrationDraftUseCase extends _i1.Mock
    implements _i51.ReadRegistrationDraftUseCase {
  MockReadRegistrationDraftUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_10(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.AuthRepository);

  @override
  _i14.Future<_i20.Either<_i21.Failure, _i19.RegistrationDraft?>> call(
    _i15.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<
                  _i20.Either<_i21.Failure, _i19.RegistrationDraft?>
                >.value(
                  _i23.dummyValue<
                    _i20.Either<_i21.Failure, _i19.RegistrationDraft?>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i14.Future<_i20.Either<_i21.Failure, _i19.RegistrationDraft?>>);
}
